spring.application.name=springboot-tricol-api

spring.datasource.url=jdbc:postgresql://localhost:5432/tricol_api
spring.datasource.username=postgres
spring.datasource.password=Badrino03
spring.jpa.hibernate.ddl-auto=update

# Liquibase Configuration
spring.liquibase.enabled=false

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# JPA Configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Server Configuration
server.port=9091

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=900000
jwt.refresh-expiration=86400000


# OAuth2 Resource Server (Keycloak)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/tricol-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/tricol-realm/protocol/openid-connect/certs

# OAuth2 Client
spring.security.oauth2.client.registration.keycloak.client-id=tricol-app
spring.security.oauth2.client.registration.keycloak.client-secret=VttftSH65whOHhCjjAwlg6AF0X0gTPhv
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/tricol-realm
spring.security.oauth2.client.provider.keycloak.token-uri=http://localhost:8080/realms/tricol-realm/protocol/openid-connect/token

# CORS
cors.allowed-origins=http://localhost:3000,http://localhost:4200
